import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_alter_initialproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialproject',
            options={'ordering': ['-featured', '-generation', '-created_at'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['-featured', '-year', '-created_at', '-id'], 'verbose_name': 'Taller Telemático', 'verbose_name_plural': 'Talleres Telemáticos'},
        ),
        migrations.AlterField(
            model_name='initialproject',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Título del Proyecto'),
        ),
        migrations.AlterField(
            model_name='initialproject',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='initialproject',
            name='members',
            field=models.TextField(help_text='Nombres separados por comas o saltos de línea', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Integrantes'),
        ),
        migrations.AddField(model_name='initialproject', name='tagline', field=models.CharField(blank=True, max_length=180, verbose_name='Bajada / slogan')),
        migrations.AddField(model_name='initialproject', name='origin', field=models.CharField(choices=[('diftel', 'Realizado por DIFTEL'), ('student', 'Realizado por estudiantes de Telemática')], db_index=True, default='student', max_length=20, verbose_name='Origen')),
        migrations.AddField(model_name='initialproject', name='student_project_type', field=models.CharField(blank=True, choices=[('course', 'Proyecto de ramo'), ('freshmen', 'Proyecto de mechones / primer año')], db_index=True, default='freshmen', max_length=20, verbose_name='Tipo de proyecto estudiantil')),
        migrations.AddField(model_name='initialproject', name='project_date', field=models.DateField(blank=True, null=True, verbose_name='Fecha del proyecto')),
        migrations.AddField(model_name='initialproject', name='course_code', field=models.CharField(blank=True, max_length=30, verbose_name='Sigla del ramo')),
        migrations.AddField(model_name='initialproject', name='course_name', field=models.CharField(blank=True, max_length=160, verbose_name='Ramo asociado')),
        migrations.AddField(model_name='initialproject', name='technologies', field=models.CharField(blank=True, help_text='Separadas por comas', max_length=300, verbose_name='Tecnologías / etiquetas')),
        migrations.AddField(model_name='initialproject', name='video_url', field=models.URLField(blank=True, max_length=500, verbose_name='Video principal')),
        migrations.AddField(model_name='initialproject', name='external_url', field=models.URLField(blank=True, max_length=500, verbose_name='Enlace externo / GitHub')),
        migrations.AddField(model_name='initialproject', name='featured', field=models.BooleanField(default=False, verbose_name='Destacado')),
        migrations.AddField(model_name='projectimage', name='caption', field=models.CharField(blank=True, max_length=220, verbose_name='Leyenda')),
        migrations.AddField(model_name='workshop', name='tagline', field=models.CharField(blank=True, max_length=180, verbose_name='Resumen corto / slogan')),
        migrations.AddField(model_name='workshop', name='event_date', field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha exacta')),
        migrations.AddField(model_name='workshop', name='involved_people', field=models.TextField(blank=True, verbose_name='Personas involucradas')),
        migrations.AddField(model_name='workshop', name='organizations', field=models.CharField(blank=True, max_length=400, verbose_name='Organizaciones involucradas')),
        migrations.AlterField(model_name='workshop', name='guia_url', field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Guía Escrita')),
        migrations.AddField(model_name='workshop', name='material_url', field=models.URLField(blank=True, max_length=500, verbose_name='Material relacionado')),
        migrations.AddField(model_name='workshop', name='video_url', field=models.URLField(blank=True, max_length=500, verbose_name='Video principal')),
        migrations.AddField(model_name='workshop', name='featured', field=models.BooleanField(default=False, verbose_name='Destacado')),
        migrations.AddField(model_name='communitymember', name='interests', field=models.CharField(blank=True, max_length=250, verbose_name='Áreas de interés')),
        migrations.AddField(model_name='communitymember', name='ask_me_about', field=models.CharField(blank=True, max_length=250, verbose_name='Puedes preguntarme sobre')),
        migrations.AddField(model_name='communitymember', name='available_to_mentor', field=models.BooleanField(default=False, verbose_name='Disponible para orientar estudiantes')),
        migrations.CreateModel(name='ProjectVideo', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(blank=True, max_length=180, verbose_name='Título')), ('url', models.URLField(max_length=500, verbose_name='URL del video')), ('order', models.IntegerField(default=0, verbose_name='Orden')), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.initialproject', verbose_name='Proyecto'))], options={'ordering': ['order', 'id'], 'verbose_name': 'Video de Proyecto', 'verbose_name_plural': 'Videos de Proyecto'}),
        migrations.CreateModel(name='WorkshopVideo', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(blank=True, max_length=180, verbose_name='Título')), ('url', models.URLField(max_length=500, verbose_name='URL del video')), ('order', models.IntegerField(default=0, verbose_name='Orden')), ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.workshop', verbose_name='Taller'))], options={'ordering': ['order', 'id'], 'verbose_name': 'Video de Taller', 'verbose_name_plural': 'Videos de Taller'}),
        migrations.CreateModel(name='CommunityEvent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=200, verbose_name='Nombre del recuerdo / actividad')), ('description', models.TextField(blank=True, verbose_name='Descripción')), ('category', models.CharField(choices=[('project', 'Proyectos'), ('workshop', 'Talleres y charlas'), ('fair', 'Ferias y muestras'), ('welcome', 'Bienvenidas y mechoneo'), ('academic', 'Vida académica'), ('social', 'Comunidad y vida estudiantil'), ('other', 'Otros recuerdos')], db_index=True, default='social', max_length=30, verbose_name='Categoría')), ('event_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha')), ('location', models.CharField(blank=True, max_length=180, verbose_name='Lugar')), ('people', models.TextField(blank=True, verbose_name='Personas / grupos involucrados')), ('featured', models.BooleanField(default=False, verbose_name='Destacado')), ('created_at', models.DateTimeField(auto_now_add=True)), ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_events', to='dashboard.initialproject', verbose_name='Proyecto relacionado')), ('related_workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_events', to='dashboard.workshop', verbose_name='Taller relacionado'))], options={'ordering': ['-featured', '-event_date', '-created_at'], 'verbose_name': 'Registro de Comunidad', 'verbose_name_plural': 'Archivo de Comunidad'}),
        migrations.CreateModel(name='CommunityMedia', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('image', models.ImageField(blank=True, null=True, upload_to='community/archive/', verbose_name='Foto')), ('video_url', models.URLField(blank=True, max_length=500, verbose_name='URL de video')), ('caption', models.CharField(blank=True, max_length=220, verbose_name='Leyenda')), ('order', models.IntegerField(default=0, verbose_name='Orden')), ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.communityevent', verbose_name='Actividad'))], options={'ordering': ['order', 'id'], 'verbose_name': 'Foto / video de comunidad', 'verbose_name_plural': 'Fotos y videos de comunidad'}),
        migrations.CreateModel(name='Course', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Sigla')), ('name', models.CharField(max_length=180, verbose_name='Nombre del ramo')), ('slug', models.SlugField(blank=True, max_length=220, unique=True)), ('semester', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Semestre')), ('plan_year', models.PositiveIntegerField(db_index=True, default=2025, verbose_name='Plan / cohorte')), ('credits', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Créditos SCT')), ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')), ('summary', models.TextField(blank=True, verbose_name='Resumen del ramo')), ('featured', models.BooleanField(default=False, verbose_name='Destacado'))], options={'ordering': ['plan_year', 'semester', 'id'], 'verbose_name': 'Ramo', 'verbose_name_plural': 'Malla y Ramos'}),
        migrations.CreateModel(name='CourseProgression', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('relationship_type', models.CharField(choices=[('progression', 'Progresión de la malla'), ('prerequisite', 'Prerrequisito'), ('recommended', 'Recomendado antes')], default='progression', max_length=20, verbose_name='Tipo de relación')), ('note', models.CharField(blank=True, max_length=220, verbose_name='Nota')), ('order', models.PositiveSmallIntegerField(default=0)), ('from_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_out', to='dashboard.course', verbose_name='Ramo previo')), ('to_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_in', to='dashboard.course', verbose_name='Ramo siguiente'))], options={'ordering': ['order', 'id'], 'verbose_name': 'Relación entre ramos', 'verbose_name_plural': 'Relaciones entre ramos'}),
        migrations.AddConstraint(model_name='courseprogression', constraint=models.UniqueConstraint(fields=('from_course', 'to_course', 'relationship_type'), name='unique_course_progression')),
        migrations.CreateModel(name='CourseResource', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('resource_type', models.CharField(choices=[('notes', 'Apuntes'), ('exam', 'Certámenes anteriores'), ('quiz', 'Controles anteriores'), ('study', 'Material de estudio')], db_index=True, max_length=20, verbose_name='Tipo')), ('title', models.CharField(max_length=200, verbose_name='Título')), ('year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')), ('academic_semester', models.PositiveSmallIntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], db_index=True, verbose_name='Semestre académico')), ('description', models.CharField(blank=True, max_length=280, verbose_name='Descripción corta')), ('file', models.FileField(blank=True, null=True, upload_to='courses/resources/', verbose_name='Archivo')), ('external_url', models.URLField(blank=True, max_length=500, verbose_name='Enlace externo')), ('uploaded_at', models.DateTimeField(auto_now_add=True)), ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='dashboard.course', verbose_name='Ramo'))], options={'ordering': ['-year', '-academic_semester', 'resource_type', 'title'], 'verbose_name': 'Material de ramo', 'verbose_name_plural': 'Materiales de ramos'}),
        migrations.CreateModel(name='CourseReview', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')), ('anonymous', models.BooleanField(default=True, verbose_name='Publicar anónimamente')), ('year_taken', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2100)], verbose_name='Año en que cursó')), ('professor', models.CharField(blank=True, max_length=160, verbose_name='Profesor/a')), ('difficulty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Dificultad')), ('workload', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Carga de trabajo')), ('usefulness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Utilidad')), ('weekly_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Horas de estudio por semana')), ('difficult_topics', models.TextField(blank=True, verbose_name='Contenidos más complejos')), ('advice', models.TextField(blank=True, verbose_name='Consejos para aprobar')), ('professor_experience', models.TextField(blank=True, verbose_name='Experiencia con docentes')), ('prior_knowledge', models.TextField(blank=True, verbose_name='Conocimientos recomendados')), ('experience', models.TextField(verbose_name='Opinión / experiencia')), ('approved', models.BooleanField(db_index=True, default=False, verbose_name='Aprobada para publicación')), ('created_at', models.DateTimeField(auto_now_add=True)), ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.course', verbose_name='Ramo'))], options={'ordering': ['-year_taken', '-created_at'], 'verbose_name': 'Opinión de ramo', 'verbose_name_plural': 'Opiniones de ramos'}),
    ]
